"""Central constants for investment-recommendations. No base URLs, weights,
or thresholds should be hardcoded anywhere else in this project."""

# --- API base URLs ---
FINNHUB_BASE_URL = "https://finnhub.io/api/v1"
COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3"
FRED_BASE_URL = "https://api.stlouisfed.org/fred"
EDGAR_BASE_URL = "https://data.sec.gov/api/xbrl"
EDGAR_TICKER_MAP_URL = "https://www.sec.gov/files/company_tickers.json"
MARKETAUX_BASE_URL = "https://api.marketaux.com/v1"

# --- Networking / rate limits ---
DEFAULT_REQUEST_TIMEOUT = 30
FINNHUB_MIN_REQUEST_INTERVAL = 1.05      # seconds; keeps us under 60/min
SEC_EDGAR_MIN_REQUEST_INTERVAL = 0.15    # ~6-7 req/sec, under SEC's 10/sec hard limit

# --- Watchlist / pipeline shape ---
WATCHLIST_PATH = "watchlist.yaml"
DEEP_DIVE_TOP_N = {"stock": 5, "etf": 3, "crypto": 2}
CIK_CACHE_PATH = "output/cik_lookup_cache.json"
CIK_CACHE_MAX_AGE_DAYS = 7
MARKETAUX_LOOKBACK_DAYS = 7

# --- Output contract ---
OUTPUT_DIR = "output"
OUTPUT_FILENAME = "dashboard_data.json"

# --- FRED macro series ---
FRED_SERIES = {
    "fed_funds_rate": {"series_id": "FEDFUNDS", "units": None},
    "cpi_yoy": {"series_id": "CPIAUCSL", "units": "pc1"},   # server-side YoY %, no client math needed
    "unemployment_rate": {"series_id": "UNRATE", "units": None},
    "treasury_10y": {"series_id": "DGS10", "units": None},
}

# --- Scoring weights (balanced-risk: equal weighting by design) ---
SCORING_WEIGHTS_EQUITY = {"valuation": 0.25, "momentum": 0.25, "volatility": 0.25, "yield": 0.25}
SCORING_WEIGHTS_CRYPTO = {"valuation": 0.30, "momentum": 0.35, "volatility": 0.35}

# --- Scoring thresholds: equities ---
PE_SWEET_SPOT_LOW = 10
PE_SWEET_SPOT_HIGH = 20
PE_EXPENSIVE_CUTOFF = 40
MOMENTUM_CAP_PCT = 25            # blended 13wk/26wk return that maxes the momentum score
MOMENTUM_OVEREXTENDED_PCT = 45   # beyond this, momentum score decays (mean-reversion risk)
BETA_SWEET_SPOT_LOW = 0.7
BETA_SWEET_SPOT_HIGH = 1.1
YIELD_SWEET_SPOT_PCT = 3.5
YIELD_DISTRESS_CUTOFF_PCT = 7.0  # dividend yield above this reads as a yield-trap signal
NEUTRAL_SCORE = 50               # default sub-score when a metric is missing

# --- Scoring thresholds: crypto ---
CRYPTO_ATH_SWEET_SPOT_LOW_PCT = -50   # % off all-time-high
CRYPTO_ATH_SWEET_SPOT_HIGH_PCT = -20
CRYPTO_MOMENTUM_CAP_PCT = 40

# --- Return estimator ---
RETURN_ESTIMATE_HORIZON_MONTHS = 12
ASSET_CLASS_BASE_RATE = {"stock": 0.08, "etf": 0.08, "crypto": 0.15}
ETF_CATEGORY_BASE_RATE_OVERRIDES = {"Bond": 0.04, "Commodity": 0.05}
BASE_SPREAD_PCT = {"stock": 12, "etf": 8, "crypto": 35}

# --- Disclaimers (single source of truth) ---
RETURN_ESTIMATE_CAVEAT = (
    "Rough estimate, not a prediction — a simple heuristic blend of recent "
    "trend and long-run asset-class averages, weighted by volatility. "
    "Actual returns will vary substantially."
)
STANDING_DISCLAIMER = (
    "This dashboard is generated by an automated heuristic pipeline for "
    "research and educational purposes only. It is not financial advice, "
    "and nothing here comes from a licensed financial advisor. Always do "
    "your own research and consult a licensed professional before making "
    "investment decisions."
)
